### ISSUE TITLE
全体ランキング

### ISSUE THREAD

**Issue by az-droid** [az-droid/Typing-bot#4]
読込み不可バグ  
```
logged in
Ignoring exception in command 全体ランキング:
Traceback (most recent call last):
File "/opt/venv/lib/python3.8/site-packages/discord/commands/core.py", line 127, in wrapped
ret = await coro(arg)
File "/opt/venv/lib/python3.8/site-packages/discord/commands/core.py", line 911, in _invoke
await self.callback(ctx, **kwargs)
File "main.py", line 89, in global_ranking
ranking: GlobalRanking = await rankings.get_global_ranking()
File "/app/utils/rankings.py", line 27, in get_global_ranking
data[int(user_id)] = float(await global_ranking_namespace.read(user_id))
TypeError: float() argument must be a string or a number, not 'dict'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/opt/venv/lib/python3.8/site-packages/discord/bot.py", line 1009, in invoke_application_command
await ctx.command.invoke(ctx)
File "/opt/venv/lib/python3.8/site-packages/discord/commands/core.py", line 359, in invoke
await injected(ctx)
File "/opt/venv/lib/python3.8/site-packages/discord/commands/core.py", line 135, in wrapped
raise ApplicationCommandInvokeError(exc) from exc
discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: float() argument must be a string or a number, not 'dist'
```
数字の入出力関係に問題あり？
KV側へのアクセスはできてるっぽい

**Comment by az-droid** [comment]
グローバルランキングとサーバー別ランキングの値の入力先が同一になっていたのを修正

**Comment by az-droid** [comment]
Close
